# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'Challenge ten seconds' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for Challenge ten seconds

pod 'AFNetworking'
pod 'JPush'

end
